import os
import random
import sys
import time
from  time import sleep
os.system ('clear')
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.1)
print ('system siap berjalan')
sleep(1)
mengetik ('>>>>>>>>      >>>>>>>>>')
sleep(2)
os.system('clear')
def main():
    password = input ('masukan kata sandi = ')
    if password == 'anak tegal':
         print ('password saya trima')
         sleep(1)
         os.system ('clear')
    else:
         os.system ('clear')
         mengetik ('salah salah')
         print ('password tidak di trima')
         exit()
sleep(1)
os.system ('clear')
main()

#banner
print ('')
mengetik ('..start..start..start..start..')
sleep(2)
print ('')
mengetik ('---------Istigfar Untuk-----------')
print ('')
mengetik ('----------------------------------')
print ('')
mengetik ('--------Masalalu------------------')
print ('')
mengetik ('----------------------------------')
print ('')
mengetik ('---------Bersukur-----------------')
print ('')
mengetik ('----------------------------------')
print ('')
mengetik ('--------Untuk---------------------')
print ('')
mengetik ('----------------------------------')
print ('')
mengetik ('--------hari ini------------------')
print ('')
mengetik ('----------------------------------')
print ('')
mengetik ('--------Ber Do,a untuk -----------')
print ('')
mengetik ('----------------------------------')
print ('')
mengetik ('--------Masa depan----------------')
print ('')
mengetik ('----------------------------------')
os.system('clear')
print ('👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀  ')
sleep(1)
print ('🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚶🚷🚷🚷🚷🚷🚷🚷🚷🚷🚷🚷🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸🚸 ')
sleep(1)
print ('\033[1;34m💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌💌')
mengetik('......assalamualaikum.......')
print ('\033[1;35m......Walaikumsalam wr.wb ')
sleep(0.2)
print ('')
sleep(2)
mengetik('\033[1;36m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
print ('')
os.system ('clear')
sleep(0.1)
print ('BANNER...BANEER..BANEER..')

print ('\033[1;33m====================================>')
print ('\033[1;33m====================================>')
print ('\033[1;34mAuthor By \033[1;0m :\033[1;32m Umay cari sukses')
print ('\033[1;34mTinggal Di= \033[1;0m :\033[1;32m Tegal jawa tegah')
print ('\033[1;34mWhatsapp  \033[1;0m :\033[1;32m 089510042221')
print ('cyber indonesia')
sleep(1)
mengetik ('´´´´´████████´´')
mengetik ('´`´███▒▒▒▒███´´´´´')
mengetik ('´´´███▒●▒▒●▒██´´´')
mengetik ('´´´███▒▒👄▒▒██´´')
mengetik ('´´██████▒▒███´´´´´')
mengetik ('´██████▒▒▒▒███´´')
mengetik ('██████▒▒▒▒▒▒███´´´´')
mengetik ('´´▓▓▓▓▓▓▓▓▓▓▓▓▓▒´´')
mengetik ('´´▒▒▒▒▓▓▓▓▓▓▓▓▓▒´´´´´')
mengetik ('´.▒▒▒´´▓▓▓▓▓▓▓▓▒´´´´´')
mengetik ('´.▒▒´´´´▓▓▓▓▓▓▓▒')
mengetik ('..▒▒.´´´´▓▓▓▓▓▓▓▒')
mengetik ('´▒▒▒▒▒▒▒▒▒▒▒▒')
mengetik ('´´´´´´´´´███████´´´´')
mengetik ('´´´´´´´´████████´´´´´´')
mengetik ('´´´´´´´█████████´´´´´')
mengetik ('´´´´´´██████████´´´')
mengetik ('´´´´´´██████████´´')
mengetik ('´´´´´´´█████████´')
mengetik ('´´´´´´´█████████´')
mengetik ('´´´´´´´´████████´´´')
mengetik ('________▒▒▒▒▒')
mengetik ('_________▒▒▒▒')
mengetik ('_________▒▒▒▒')
mengetik ('________▒▒_▒▒')
mengetik ('_______▒▒__▒▒')
mengetik ('_____ ▒▒___▒▒')
mengetik ('_____▒▒___▒▒')
mengetik ('____▒▒____▒▒')
mengetik ('___▒▒_____▒▒')
mengetik ('_███______▒▒')
mengetik ('█_███____███')
mengetik ('█__███_ _█_███')
print ('##############################################')
print ('Slamat Datang')
sleep(1)
print ('(((((pilih Menu)))))')
print ('Start..✈✈✈✈✈✈✈✈✈✈✈✈✈✈.........✈✈✈✈✈✈✈✈')
print ('Istigfar untuk')
print ('-----------------------')
print ('Masalalu')
print ('-----------------------')
print ('Bersukur')
print ('------------------------')
print ('Untuk')
print ('------------------------')
print ('Hari ini')
print ('------------------------')
print ('Ber Do,a untuk ')
print ('------------------------')
print ('Masa depan')
print ('------------------------')
print ('No = 1 update && upgrade')
sleep (0.2)
print ('No = 2 install pip')
sleep(0.3)
print ('No = 3 install system ')
print ('No = 4 google')
print ('No = 5 Tools lengkap')
print ('No = 6 keluar')
def main ():
    pilih = input (' == pilih menu == ')
    if pilih == '1' or pilih == '0.1':
         os.system('clear')
         print ('Loding..')
         mengetik  ('apt install update && apt insta upgrade')
         sleep(1)
         print ('instaling data')
         sleep(1)
         os.system('pkg install update && pkg install upgrade')
    if pilih == '2' or pilih == '02':
        os.system('clear')
        print (' loding..')
        mengetik ('requests pip ')
        sleep(2)
        print ('pip install requests')
        sleep(2)
        os.system('pip install requests')
    if pilih == '3' or pilih == '03':
        os.system('clear')
        print ('loding..')
        mengetik ('install system siap meluncur')
        sleep(3)
        print ('system akan di install')
        sleep(3)
        os.system('git clone https://github.com/umaycarisukses/tools.git')
    if pilih == '4' or pilih =='04':
        os.system('clear')
        print ('')
        mengetik ('Loding........')
        sleep(4)
        os.system('clear')
    if pilih == '5' or pilih == '05':
       os.system('clear')
       print ('')
       mengetik('SISTEM LENGKAP AKAN DI INSTALL')
       sleep(5)
       os.system('git clone https://github.com/umaycariaukses/tools.git')
    if pilih == '6' or pilih == '06':
       os.system('clear')
       print ('')
       mengetik('tools lengkap boos')
       sleep(5)
       os.system('exit')
main()
